//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.27 at 10:07:32 AM VET 
//


package auth.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ADResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ADResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://tempuri.org/}errorHandler"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="loginSuccess" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="resetPassword" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="allowAccess" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="infoMessage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ADResponse", propOrder = {
    "loginSuccess",
    "resetPassword",
    "allowAccess",
    "infoMessage"
})
public class ADResponse
    extends ErrorHandler
{

    protected boolean loginSuccess;
    protected boolean resetPassword;
    protected boolean allowAccess;
    protected String infoMessage;

    /**
     * Gets the value of the loginSuccess property.
     * 
     */
    public boolean isLoginSuccess() {
        return loginSuccess;
    }

    /**
     * Sets the value of the loginSuccess property.
     * 
     */
    public void setLoginSuccess(boolean value) {
        this.loginSuccess = value;
    }

    /**
     * Gets the value of the resetPassword property.
     * 
     */
    public boolean isResetPassword() {
        return resetPassword;
    }

    /**
     * Sets the value of the resetPassword property.
     * 
     */
    public void setResetPassword(boolean value) {
        this.resetPassword = value;
    }

    /**
     * Gets the value of the allowAccess property.
     * 
     */
    public boolean isAllowAccess() {
        return allowAccess;
    }

    /**
     * Sets the value of the allowAccess property.
     * 
     */
    public void setAllowAccess(boolean value) {
        this.allowAccess = value;
    }

    /**
     * Gets the value of the infoMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInfoMessage() {
        return infoMessage;
    }

    /**
     * Sets the value of the infoMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInfoMessage(String value) {
        this.infoMessage = value;
    }

}
