//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.27 at 10:07:32 AM VET 
//


package auth.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ChangePassADResult" type="{http://tempuri.org/}errorHandler" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "changePassADResult"
})
@XmlRootElement(name = "ChangePassADResponse")
public class ChangePassADResponse {

    @XmlElement(name = "ChangePassADResult")
    protected ErrorHandler changePassADResult;

    /**
     * Gets the value of the changePassADResult property.
     * 
     * @return
     *     possible object is
     *     {@link ErrorHandler }
     *     
     */
    public ErrorHandler getChangePassADResult() {
        return changePassADResult;
    }

    /**
     * Sets the value of the changePassADResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link ErrorHandler }
     *     
     */
    public void setChangePassADResult(ErrorHandler value) {
        this.changePassADResult = value;
    }

}
