//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.27 at 10:07:32 AM VET 
//


package auth.wsdl;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the auth.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: auth.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LoginAD }
     * 
     */
    public LoginAD createLoginAD() {
        return new LoginAD();
    }

    /**
     * Create an instance of {@link LoginADResponse }
     * 
     */
    public LoginADResponse createLoginADResponse() {
        return new LoginADResponse();
    }

    /**
     * Create an instance of {@link ADResponse }
     * 
     */
    public ADResponse createADResponse() {
        return new ADResponse();
    }

    /**
     * Create an instance of {@link ChangePassAD }
     * 
     */
    public ChangePassAD createChangePassAD() {
        return new ChangePassAD();
    }

    /**
     * Create an instance of {@link ChangePassADResponse }
     * 
     */
    public ChangePassADResponse createChangePassADResponse() {
        return new ChangePassADResponse();
    }

    /**
     * Create an instance of {@link ErrorHandler }
     * 
     */
    public ErrorHandler createErrorHandler() {
        return new ErrorHandler();
    }

}
